version: "3.8"

services:
  prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      restart: on-failure
      volumes:
        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        - ./data/prometheus_data:/prometheus
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/etc/prometheus/console_libraries'
        - '--web.console.templates=/etc/prometheus/consoles'
        - '--web.enable-lifecycle'
      ports:
        - "9090:9090"

  # node-exporter:
  #   image: prom/node-exporter:latest
  #   container_name: node-exporter
  #   restart: unless-stopped
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /:/rootfs:ro
  #   command:
  #     - '--path.procfs=/host/proc'
  #     - '--path.rootfs=/rootfs'
  #     - '--path.sysfs=/host/sys'
  #     - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
  #   expose:
  #     - 9100

  json-exporter:
    image: quay.io/prometheuscommunity/json-exporter
    container_name: json-exporter
    restart: unless-stopped
    volumes:
      - ./prometheus/exporters/json-exporter/config.yml:/config.yml
    command:
      - '--config.file=/config.yml'
    expose:
      - 7979

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    restart: on-failure
    hostname: grafana
    depends_on:
      - prometheus
    volumes:
      - ./data/grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
