global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["127.0.0.1:9090"]
  - job_name: "beacon node"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:8080"]
  # - job_name: "node_exporter"
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ["node-exporter:9100"]
  - job_name: "validator"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:8081"]
  - job_name: json_exporter
    static_configs:
      - targets:
          - json-exporter:7979
  - job_name: json
    metrics_path: /probe
    static_configs:
      - targets:
          - https://api.coingecko.com/api/v3/simple/price?ids=lukso-token&vs_currencies=usd
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: json-exporter:7979
